# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: f97/vaultwarden

    # Description displayed on the app list
    description: |-
        Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            📖 [Documentation](https://github.com/dani-garcia/vaultwarden/wiki)

        # Displayed after deployment
        end: |-
            🎉🎉🎉 Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

            > *NOTE*: Enable WebSocket Support in the app's HTTP settings.
            > Also make sure to allow port `3012` through your firewall.
            > Also enable HTTPS.

            > *NOTE*: There's a lot of environment variables you can set.
            > Click [here](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for a complete list.

    # Documentation Link
    documentation: https://github.com/dani-garcia/vaultwarden/wiki

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag to install.  
                Click [here](https://hub.docker.com/r/vaultwarden/server/tags) for a list of available tags.
            defaultValue: alpine
            validRegex: /^(?:\d+\.\d+\.\d+(?:\.\d+)?)(?:-alpine)?(?:-(?:arm|amd)(?:64|32)(?:v\d+)?)|alpine?$/

        # Variable for time zone
        -   id: $$cap_tz
            label: Time Zone
            description: |-
                Specify your system's time zone.  
                Click [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of available time zones.
            defaultValue: Asia/Ho_Chi_Minh
            validRegex: /^\w+\/\w+$/

        # Variable for user signups enabled/disabled
        -   id: $$cap_admin_token
            label: Admin token?
            description: |-
                > *NOTE*: You should probably disable this after you sign-up.

# Define services
services:

    # Bitwarden service
    $$cap_appname:

        # Use official image
        image: vaultwarden/server:$$cap_appversion

        # Set hostname (f.e. vaultwarden.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # The domain which vaultwarden runs on, I use https because I doubt anyone will run vaultwarden on non-https 
            DOMAIN: https://$$cap_appname.$$cap_root_domain

            # Timezone
            TZ: $$cap_tz

            # Enable websocket notifications
            WEBSOCKET_ENABLED: true

            # Disable user sign-ups
            ADMIN_TOKEN: $$cap_admin_token

        # Define ports
        ports:

            # WebSocket port
            - 3012:3012

        # Define volumes
        volumes:

            # Volume containing database data and config
            - $$cap_appname-data:/data
